"""Rasterise the hand-authored SVG diagrams in figures/ to PNG.

    .venv/bin/python scripts/render_diagrams.py

The two method diagrams are written as SVG by hand rather than generated by
matplotlib: they are schematics, not plots, and matplotlib's text placement is
the wrong tool for boxes-and-arrows. The SVG is the source of truth; the PNG
exists for slide decks and for anything that cannot embed vector art.

Two gotchas worth knowing before editing the SVGs, both of which produced
figures that looked fine in a browser and broke when rasterised:

  * Unicode subscript codepoints (U+2080 and friends) are missing from most
    sans faces and render as tofu boxes. Write indices as `D(t)`.
  * `<tspan dy=...>` inside a `text-anchor="middle"` element makes several
    renderers mis-measure the advance width, which overlaps the glyphs. Keep
    centred lines as a single run.
"""

from __future__ import annotations

import sys
from pathlib import Path

FIGURES = Path(__file__).resolve().parent.parent / "figures"
DIAGRAMS = ["diagram_firewall", "diagram_verdict_loop"]
WIDTH = 1800


def main() -> int:
    try:
        import cairosvg
    except ImportError:
        print("pip install cairosvg", file=sys.stderr)
        return 1

    missing = [n for n in DIAGRAMS if not (FIGURES / f"{n}.svg").exists()]
    if missing:
        print(f"missing sources: {missing}", file=sys.stderr)
        return 1

    for name in DIAGRAMS:
        src, dst = FIGURES / f"{name}.svg", FIGURES / f"{name}.png"
        cairosvg.svg2png(url=str(src), write_to=str(dst), output_width=WIDTH)
        print(f"{src.name} -> {dst.name} ({dst.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
